version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  your_java_app:
    build: 
      context: /D:/Eommerce-Application/Ecom_Application
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://localhost:5432/ecommerce
      DB_USER: postgres
      DB_PASSWORD: root

volumes:
  postgres_data:


